'use strict';

const EVENT_ACTIONS = [
  'SAMPLE_CREATED',
  'SAMPLE_UPDATED',
  'STATUS_CHANGED',
  'LOCATION_CHANGED',
  'DOCUMENT_UPLOADED',
  'DOCUMENT_DELETED',
  'RATING_ADDED',
  'RATING_UPDATED',
  'RATING_DELETED',
];

module.exports = {
  EVENT_ACTIONS,
};
